import { beforeEach, describe, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import { confirmImport } from "@/lib/import/actions";
import type { ParsedRow } from "@/lib/import/parse-file";
import { ensureRecurringEntriesForMonth } from "@/lib/recurring/generate";
import { createSession, setSessionCookie } from "@/lib/auth/session";
import { __resetMockCookies } from "@/tests/mocks/next-headers";
import {
  createTestUser,
  db,
  entryTags,
  financialEntries,
  recurringEntries,
  recurringEntryTags,
  tags,
  truncateAll,
} from "@/tests/db-helpers";

async function loginAs(userId: string) {
  const { token, expiresAt } = await createSession(userId);
  await setSessionCookie(token, expiresAt);
}

async function seedTemplate(userId: string, overrides: Partial<typeof recurringEntries.$inferInsert> = {}) {
  const [row] = await db
    .insert(recurringEntries)
    .values({
      userId,
      type: "EXPENSE",
      description: "Energia",
      amountCents: null,
      dueDay: 10,
      active: true,
      createdAt: new Date("2026-01-01T00:00:00Z"),
      ...overrides,
    })
    .returning();
  return row;
}

function row(rowNumber: number, values: ParsedRow["values"]): ParsedRow {
  return { rowNumber, values };
}

beforeEach(async () => {
  await truncateAll();
  __resetMockCookies();
});

describe("confirmImport — linked to a recorrente", () => {
  it("inserts a new financial_entries row with recurringEntryId, classification FIXED, and the template's tags snapshotted", async () => {
    const user = await createTestUser();
    await loginAs(user.id);
    const [tag] = await db.insert(tags).values({ userId: user.id, name: "Casa" }).returning();
    const template = await seedTemplate(user.id);
    await db.insert(recurringEntryTags).values({ recurringEntryId: template.id, tagId: tag.id });

    const result = await confirmImport([
      row(2, { data: "2026-02-10", descricao: "Conta de luz", valor: "220,00", recorrente: "Energia" }),
    ]);

    expect(result).toEqual({ imported: 1, updated: 0, failed: [] });

    const rows = await db.select().from(financialEntries).where(eq(financialEntries.userId, user.id));
    expect(rows).toHaveLength(1);
    const [entry] = rows;
    expect(entry.recurringEntryId).toBe(template.id);
    expect(entry.classification).toBe("FIXED");
    expect(entry.type).toBe("EXPENSE");
    expect(entry.amountCents).toBe(22000);
    expect(entry.status).toBe("PAID");

    const links = await db.select().from(entryTags).where(eq(entryTags.entryId, entry.id));
    expect(links.map((l) => l.tagId)).toEqual([tag.id]);
  });

  it("updates the existing month's entry instead of duplicating on reimport", async () => {
    const user = await createTestUser();
    await loginAs(user.id);
    await seedTemplate(user.id, { amountCents: 20000 });

    const importRow = row(2, {
      data: "2026-02-12",
      descricao: "Conta de luz",
      valor: "225,50",
      recorrente: "Energia",
      status: "Pago",
    });

    const first = await confirmImport([importRow]);
    expect(first).toEqual({ imported: 1, updated: 0, failed: [] });

    const second = await confirmImport([importRow]);
    expect(second).toEqual({ imported: 0, updated: 1, failed: [] });

    const rows = await db.select().from(financialEntries).where(eq(financialEntries.userId, user.id));
    expect(rows).toHaveLength(1);
    expect(rows[0].amountCents).toBe(22550);
  });

  it("updates a stub already generated by ensureRecurringEntriesForMonth instead of duplicating", async () => {
    const user = await createTestUser();
    await loginAs(user.id);
    const template = await seedTemplate(user.id, { amountCents: 20000, dueDay: 10 });

    await ensureRecurringEntriesForMonth(user.id, "2026-02");
    const beforeImport = await db.select().from(financialEntries).where(eq(financialEntries.recurringEntryId, template.id));
    expect(beforeImport).toHaveLength(1);
    expect(beforeImport[0].status).toBe("PENDING");

    const result = await confirmImport([
      row(2, { data: "2026-02-10", descricao: "Conta de luz", valor: "199,90", recorrente: "Energia" }),
    ]);
    expect(result).toEqual({ imported: 0, updated: 1, failed: [] });

    const rows = await db.select().from(financialEntries).where(eq(financialEntries.recurringEntryId, template.id));
    expect(rows).toHaveLength(1);
    expect(rows[0].amountCents).toBe(19990);
    expect(rows[0].status).toBe("PAID");
  });

  it("does not link to another user's recurring template of the same name", async () => {
    const owner = await createTestUser({ username: "import-owner" });
    const attacker = await createTestUser({ username: "import-attacker" });
    await seedTemplate(owner.id);
    await loginAs(attacker.id);

    const result = await confirmImport([
      row(2, { data: "2026-02-10", descricao: "Conta de luz", valor: "100,00", recorrente: "Energia" }),
    ]);

    expect(result.imported).toBe(0);
    expect(result.updated).toBe(0);
    expect(result.failed).toHaveLength(1);

    const attackerRows = await db.select().from(financialEntries).where(eq(financialEntries.userId, attacker.id));
    expect(attackerRows).toHaveLength(0);
  });
});

describe("confirmImport — plain rows", () => {
  it("creates a VARIABLE entry with tags resolved/created via resolveTagIds", async () => {
    const user = await createTestUser();
    await loginAs(user.id);
    const [existingTag] = await db.insert(tags).values({ userId: user.id, name: "Mercado" }).returning();

    const result = await confirmImport([
      row(2, {
        data: "2026-02-03",
        descricao: "Compras do mês",
        valor: "350,00",
        tipo: "Despesa",
        tags: "mercado, Casa",
      }),
    ]);

    expect(result).toEqual({ imported: 1, updated: 0, failed: [] });

    const [entry] = await db.select().from(financialEntries).where(eq(financialEntries.userId, user.id));
    expect(entry.classification).toBe("VARIABLE");
    expect(entry.recurringEntryId).toBeNull();

    const links = await db.select().from(entryTags).where(eq(entryTags.entryId, entry.id));
    expect(links).toHaveLength(2);

    const allTags = await db.select().from(tags).where(eq(tags.userId, user.id));
    // "mercado" reused the existing case-insensitive match; "Casa" was created.
    expect(allTags).toHaveLength(2);
    expect(allTags.find((t) => t.id === existingTag.id)?.name).toBe("Mercado");
  });

  it("collects row-level failures without aborting the rest of the batch", async () => {
    const user = await createTestUser();
    await loginAs(user.id);

    const result = await confirmImport([
      row(2, { data: "2026-02-03", descricao: "Válida", valor: "10,00", tipo: "Despesa" }),
      row(3, { data: "data-invalida", descricao: "Quebrada", valor: "10,00", tipo: "Despesa" }),
    ]);

    expect(result.imported).toBe(1);
    expect(result.failed).toEqual([{ rowNumber: 3, error: expect.stringMatching(/Data inválida/) }]);

    const rows = await db.select().from(financialEntries).where(eq(financialEntries.userId, user.id));
    expect(rows).toHaveLength(1);
  });
});
